### ISSUE TITLE
[DISCUSS] 코틀린 생성자 내/외부에 따른 지연로딩 방식

### ISSUE THREAD

**Issue by semi-cloud** [depromeet/13th-8team-backend#15]
## 논의 사항
+ 생성자 안에서 지연 로딩이면 `val`
+ 생성자 밖에서 지연 로딩이면 `var`

> 왜 두 방식에서 선언 방식이 달라지는 것인가?

**Comment by gunh0** [comment]
### 지연 로딩

**메모리 구조에서 생성자 안에서 지연 로딩된 변수인 경우 (`val`):**
생성자 안에서 변수를 선언하고 초기화하지 않은 경우, 해당 변수는 메모리에 공간이 할당되지 않음
변수가 초기화되기 전까지는 해당 메모리 공간에 아무런 값도 존재하지 않음

**메모리 구조에서 생성자 밖에서 지연 로딩된 변수인 경우 (`var`):**
생성자 밖에서 변수를 선언하고 초기화하지 않은 경우, 해당 변수는 메모리에 공간이 할당
변수의 초기값은 일반적으로 해당 데이터 타입의 기본값으로 설정 예를 들어, 정수형 변수의 기본값은 0


**장점**
- 성능 개선: 지연 로딩은 초기화되지 않은 객체나 데이터를 불필요하게 로드하지 않고, 필요한 시점에만 생성 그래서 자원이 절약됨
- 지연 로딩은 필요에 따라 객체를 생성하므로, 애플리케이션의 확장성을 향상시킬 수 있지만, 대규모 데이터 처리나 복잡한 작업에도 유연하게 대응하기 위해서는 객체 소멸이 정말 중요!

**단점**
- 초기 접근 지연
- 코드의 복잡도 올라감
- 메모리 릭 (지연 로딩된 객체나 데이터는 사용이 끝나더라도 메모리에 남을 수 있음)
- 병목 현상 발생 (여러 개의 지연 로딩된 객체나 데이터에 동시에 접근할 경우)

**결론**
- `var` 방식은 메모리 사용량을 미리 할당하는 방식이므로 메모리 사용량을 상대적으로 예측하는 것이 쉬워짐
- `val` is same as the final modifier in java. As you should probably know that we can not assign to a final variable again but can change its properties.
- 애초에 두 가지 변수 선언의 차이는 담으려는 데이터 변경 여부가 중요함 (지연 로딩보다도...)
variables defined with `var` are mutable(Read and Write)
variables defined with `val` are immutable(Read only)
