### ISSUE TITLE
[DISCUSS] GitHub Action Deploy Strategy

### ISSUE THREAD

**Issue by gunh0** [depromeet/13th-8team-backend#24]
## 논의 사항
- AWS S3 빌드파일 압축해서 업로드 -> AWS EC2 배포 (CodeDeploy 활용)
- AWS ECR 에 도커 이미지 업로드 -> AWS ECS 배포 (Task Definition 활용)

**Comment by semi-cloud** [comment]
@gunh0 
찾아보니 `Task Definition` 로 직접 하는거보다 `Service` 사용하면 자동으로 관리해주는게 많던데 이거는 고려 안하신 이유가 있을까요?

1. 로드 밸런싱
2. 오토 스케일링
3. 컨테이너 헬스 체킹..등등

일단 S3 + CodeDeploy는 해봤어서 개인적으로 이번에는 ECS 경험해보고 싶습니다
흠 근데 당장 도입하기에는 개발이 급해서 일단 NCP로 해두고 기능 호다닥 끝내고 고도화 작업해도 좋을 것 같아요

**Comment by semi-cloud** [comment]
<img src="https://github.com/depromeet/pumping-server/assets/71436576/5454afc9-4efa-464e-85d6-11fd7ee647c6" width=50% height=50%>

**Comment by gunh0** [comment]
ssh deploy
