### ISSUE TITLE
[DISCUSS] Test NoSQL embedded VS reference type performance

### ISSUE THREAD

**Issue by semi-cloud** [depromeet/13th-8team-backend#30]
## 논의 사항
+ Sports 테이블 참조 타입인 경우랑 임베디드 타입인 경우 조회 속도 차이
+ Sql 쿼리문 여러번 VS 방대한 양 데이터 한번에 가져오기

참고 자료
https://dev.gmarket.com/32
https://betterprogramming.pub/embedded-vs-referenced-documents-in-mongodb-how-to-choose-correctly-for-increased-performance-d267769b8671

**Comment by gunh0** [comment]
do not use reference type
