### ISSUE TITLE
[REFACTOR] Docs file is created in the local

### ISSUE THREAD

**Issue by Gyuchool** [depromeet/13th-8team-backend#31]
## 리팩토링 내용
<img width="295" alt="스크린샷 2023-06-10 오후 9 26 06" src="https://github.com/depromeet/pumping-server/assets/60054318/dcc24664-0ab1-4c6b-b0a7-b3c3d9bdb2e9">

로컬에서 빌드하면 로컬 파일에도 docs하위 파일들이 생기네여

불필요하고 용량만 차지해서 아예 copy하지 않도록 gradle script 수정하려고 합니다.

**Comment by semi-cloud** [comment]
@Gyuchool 
로컬에서 문서 커스텀 할때 바로 변경 사항 확인할 수 있도록 일부로 설정해두었습니다!
확실히 용량 차지하는 단점이 있겠네요. [AsciiDoc Plugin](https://plugins.jetbrains.com/plugin/7391-asciidoc) 사용하는 것으로 바꿀까요?

**Comment by Gyuchool** [comment]
아 일부러 남겨둔거야? 
인텔리제이에서 어차피 지원해줘서 로컬에서 확인 잘 안하잖수, 파일 용량만 커질거같아서 제거하려했으
