### ISSUE TITLE
[DISCUSS] 개발 언어 및 버전 논의

### ISSUE THREAD

**Issue by semi-cloud** [depromeet/13th-8team-backend#4]
## 논의 사항
- [x] 자바 or 코틀린
- [x] `JDK 11` or `JDK 17`

## 참고 사항
1. 언어
저는 개인적으로 `null` 안전성이나 작성해야 하는 코드가 너무 간결해져서 코틀린을 사용하고 싶지만..!!
두 분 모두 안써보셨으면 이번 기회에 공부해 보시는건..어떠신가요..!? (하지만 당연히 다수결에 따르겠습니당)

2. JDK 버전
[우리팀이 JDK 17을 도입한 이유](https://techblog.gccompany.co.kr/우리팀이-jdk-17을-도입한-이유-ced2b754cd7) 보면 JDK 17에서 디벨롭된 기능들이 많은 것 같아요

각자 의견 남겨주시면 감사하겠습니다:)

**Comment by gunh0** [comment]
코믿 + 자바17
