### ISSUE TITLE
[DISCUSS] DB config management: Flyway

### ISSUE THREAD

**Issue by gunh0** [depromeet/13th-8team-backend#6]
- [x] DB 형상 관리 방법 결정

**Comment by ding-co** [comment]
확인했습니다~

**Comment by semi-cloud** [comment]
### 변경 사항
+ `Flyway` 에서 `mongoDB`을 지원하지 않는 이슈로 인해 사용 X

**Comment by gunh0** [comment]
- https://github.com/depromeet/13th-8team-backend/blob/main/docker-compose.yml
- https://github.com/depromeet/13th-8team-backend/blob/main/init-mongo.js

<br/>

**_init-mongo.js 스크립트는 MongoDB에서 사용, GitOps 관점의 DB 관리_**

설명:
- mydb 데이터베이스를 선택하고, mycollection 컬렉션을 생성

참고:
-  GitOps 방법론에서는 이 스크립트를 Git 저장소에 저장하고, 변경 사항을 GitOps 도구를 사용하여 MongoDB 인프라스트럭처에 자동으로 적용하는 것을 의미
- 이를 통해 변경 사항의 추적 및 복구가 용이해지며, 버전 관리를 통해 인프라스트럭처의 상태가 항상 일관성을 유지할 수 있음
